<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <LangVersion>5</LangVersion>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>EasyRDP.Server.Wpf</AssemblyName>
    <RootNamespace>EasyRDP.Server.Wpf</RootNamespace>
    <StartupObject>EasyRDP.Server.Wpf.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\aly\client\aly-client-sdk\AlyClient.CSharpSDK\AlyClient.CSharpSDK\AlyClient.CSharpSDK.csproj" />
    <ProjectReference Include="..\EasyRDP.Core\EasyRDP.Core.csproj" />
    <ProjectReference Include="..\..\EasyDesk\src\EasyDesk.Core\EasyDesk.Core.csproj" />
    <ProjectReference Include="..\..\EasyDesk\src\EasyDesk.Windows\EasyDesk.Windows.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="4.6.3" />
  </ItemGroup>

</Project>
