<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- 支持 x86 / x64 双架构测试 -->
    <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EasyRDP.Core\EasyRDP.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\libs\openh264\x64\openh264.dll" Link="openh264\x64\openh264.dll"
             CopyToOutputDirectory="PreserveNewest" Visible="false"/>
    <Content Include="..\..\libs\openh264\x86\openh264.dll" Link="openh264\x86\openh264.dll"
             CopyToOutputDirectory="PreserveNewest" Visible="false"/>
  </ItemGroup>

</Project>
