<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EasyRDP.Core\EasyRDP.Core.csproj" />
    <ProjectReference Include="..\..\aly\client\aly-client-sdk\AlyClient.CSharpSDK\AlyClient.CSharpSDK\AlyClient.CSharpSDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\RelayCommand.cs" Link="RelayCommand.cs" />
    <Compile Include="..\Shared\SecretProtector.cs" Link="SecretProtector.cs" />
    <Page Include="..\Shared\UiStyles.xaml" Link="UiStyles.xaml" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\libs\openh264\x86\openh264.dll"
             Link="openh264\x86\openh264.dll"
             CopyToOutputDirectory="PreserveNewest" Visible="false"/>
    <Content Include="..\..\libs\openh264\x64\openh264.dll"
             Link="openh264\x64\openh264.dll"
             CopyToOutputDirectory="PreserveNewest" Visible="false"/>
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
