<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net40</TargetFramework>
    <LangVersion>5</LangVersion>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>EasyRDP.Client.Wpf</AssemblyName>
    <RootNamespace>EasyRDP.Client.Wpf</RootNamespace>
    <StartupObject>EasyRDP.Client.Wpf.App</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\aly\client\aly-client-sdk\AlyClient.CSharpSDK\AlyClient.CSharpSDK\AlyClient.CSharpSDK.csproj" />
    <ProjectReference Include="..\EasyRDP.Core\EasyRDP.Core.csproj" />
    <ProjectReference Include="..\EasyRDP.Client.Common\EasyRDP.Client.Common.csproj" />
    <ProjectReference Include="..\..\EasyDesk\src\EasyDesk.Core\EasyDesk.Core.csproj" />
    <ProjectReference Include="..\..\EasyDesk\src\EasyDesk.Windows\EasyDesk.Windows.csproj" />
  </ItemGroup>

</Project>
